[package]
name = "rust-driver-ping-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
env_logger = "0.11.8"
log = "0.4.28"
mongodb = "3.3.0"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full", "rt"] }
